import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { WindowDimensionContextProvider } from "@/hooks/useWindowDimension";

const nb_international_regular = localFont({
  src: "../public/typography/NBInternationalProReg.woff2",
  display: "swap",
  variable: "--font-nb-international",
  weight: "400",
});

const nb_international_mono = localFont({
  src: "../public/typography/NBInternationalProMono.woff2",
  display: "swap",
  variable: "--font-nb-international-mono",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nb_international_regular.className} ${nb_international_regular.variable} ${nb_international_mono.variable}`}
      >
        <WindowDimensionContextProvider>
          {children}
        </WindowDimensionContextProvider>
      </body>
    </html>
  );
}
