import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { WindowDimensionContextProvider } from "@/hooks/useWindowDimension";
import PointerContextProvider from "@/components/PointerContextProvider/PointerContextProvider";
import Head from "next/head";

const nb_international_regular = localFont({
  src: "../public/typography/NBInternationalProReg.woff2",
  display: "swap",
  variable: "--font-nb-international",
  weight: "400",
});

const nb_international_mono = localFont({
  src: "../public/typography/NBInternationalProMono.woff2",
  display: "swap",
  variable: "--font-nb-international-mono",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          src="https://app.viral-loops.com/widgetsV2/core/loader.js"
          data-campaign-id="2X8NEjvQ9c5KJYR7178Sizt9pxM"
          id="viral-loops-loader"
        ></script>
        <title>Superpower</title>
        <meta
          content="Become the best version&nbsp;of&nbsp;yourself with the world's most advanced health platform."
          name="description"
        />
        <meta content="Superpower" property="og:title" />
        <meta
          content="Become the best version&nbsp;of&nbsp;yourself with the world's most advanced health platform."
          property="og:description"
        />
        <meta
          content="https://daybreak-superpower.netlify.app/og.png"
          property="og:image"
        />
        <meta content="Superpower" property="twitter:title" />
        <meta
          content="Become the best version&nbsp;of&nbsp;yourself with the world's most advanced health platform."
          property="twitter:description"
        />
        <meta
          content="https://daybreak-superpower.netlify.app/og.png"
          property="twitter:image"
        />
        <meta property="og:type" content="website" />
        <meta content="summary_large_image" name="twitter:card" />
      </head>
      <body
        className={`
          ${nb_international_regular.className} 
          ${nb_international_regular.variable} 
          ${nb_international_mono.variable} 
          overflow-x-hidden
        `}
      >
        <WindowDimensionContextProvider>
          <PointerContextProvider>{children}</PointerContextProvider>
        </WindowDimensionContextProvider>
      </body>
    </html>
  );
}
